version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db.mv.db
    volumes:
      - metabase-data:/metabase-data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Sample PostgreSQL database with sample data for prototyping
  postgres:
    image: postgres:15
    container_name: metabase-postgres
    environment:
      POSTGRES_DB: sample_data
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sample-data:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  metabase-data:
  postgres-data:
