# fly.toml app configuration file generated for reporting-metabase on 2025-08-25T13:35:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reporting-metabase'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'
  MB_JETTY_HOST = '0.0.0.0'

[processes]
  app = "java -jar /app/metabase.jar"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
