services:
  - type: web
    name: reporting-metabase
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: MB_DB_TYPE
        value: h2
      - key: MB_DB_FILE
        value: /metabase-data/metabase.db.mv.db
